version: 2.1
orbs:
  node: circleci/node@5.1
jobs:
  build:
    docker:
      - image: 'cimg/node:16.17.1'
    steps:
      - node/install:
          node-version: '16.17.1'
      - checkout
      - run:
          name: Install Vercel CLI
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            echo "Install vercel cli"
            npm i -g vercel
            echo "Vercel --version"
            echo $(vercel --version)
      - run:
          name: Install Client Dependecies
          command: |
            echo "Install client dependecies"
            npm run client:install
      - run:
          name: Install Server Dependecies
          command: |
            echo "Install server dependecies"
            npm run server:install
      - run:
          name: Build Client App
          command: |
            echo "Build client app"
            npm run client:build
      - run:
          name: Build Server App
          command: |
            echo "Build server app"
            npm run server:build
  deploy:
    docker:
      - image: 'cimg/node:16.17.1'
    steps:
      - node/install:
          node-version: '16.17.1'
      - checkout
      - run:
          name: Add Server Environment variables
          command: |
            echo $(vercel --version)
